name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Build APK
        run: flutter build apk --release
      - name: Rename APK
        run: mv build/app/outputs/flutter-apk/app-release.apk ./intens_monitor.apk
      - name: Archive APK
        uses: actions/upload-artifact@v1
        with:
          name: android-build
          path: ./intens_monitor.apk
  build_ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Build IOS
        run: flutter build ios --release --no-codesign
      - name: Archive IOS
        uses: actions/upload-artifact@v1
        with:
          name: ios-build
          path: build/ios/iphoneos
  build_web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Build web
        uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /intens_monitor/
